"""added unique columns

Revision ID: 2502ce5d9fa5
Revises: db6195f681f6
Create Date: 2018-11-19 13:13:24.971856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2502ce5d9fa5'
down_revision = 'db6195f681f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('users', 'full_name',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('users', 'password',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('users', 'username',
                    existing_type=sa.TEXT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('users', 'password',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('users', 'full_name',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('users', 'email',
                    existing_type=sa.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###
