"""added delete orphan objects

Revision ID: 6727e8243a70
Revises: 8db4e7e07869
Create Date: 2018-11-30 15:41:29.461245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6727e8243a70'
down_revision = '8db4e7e07869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_users_followed_id'), 'users_users', ['followed_id'], unique=False)
    op.create_index(op.f('ix_users_users_follower_id'), 'users_users', ['follower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_users_follower_id'), table_name='users_users')
    op.drop_index(op.f('ix_users_users_followed_id'), table_name='users_users')
    # ### end Alembic commands ###
