"""changed profile photo from URL to file name only

Revision ID: 8c0d7ee763b4
Revises: 86620fb9326d
Create Date: 2018-11-24 18:38:24.304116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0d7ee763b4'
down_revision = '86620fb9326d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_name', sa.Text(), server_default='generic_profile_pic.png', nullable=False))
    op.drop_column('users', 'profile_picture_URL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_URL', sa.TEXT(), server_default=sa.text("'https://s3.amazonaws.com/ahmed-clone-instagram/generic_profile_pic.png'::text"), autoincrement=False, nullable=False))
    op.drop_column('users', 'profile_picture_name')
    # ### end Alembic commands ###
