"""added is_approved column to followings

Revision ID: fbf21f2748f8
Revises: 6727e8243a70
Create Date: 2018-12-03 01:14:09.996285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf21f2748f8'
down_revision = '6727e8243a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_users', sa.Column('is_approved', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_users', 'is_approved')
    # ### end Alembic commands ###
